#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication gmshToFoam flatplate_69x49.msh
runApplication transformPoints -scale '(1 0.01 1)'
cp -r 0.org 0
runApplication changeDictionary

# ----------------------------------------------------------------- end-of-file
