#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0 *.dat *.e[0-9]* *.o[0-9]* balances

# ----------------------------------------------------------------- end-of-file
